library(shinydashboard)
library(AnnotationDbi)
library(org.Mm.eg.db) #Mus musculus
library(org.Hs.eg.db) #Homo sapiens
#library(org.Dr.eg.db) #Danio rerio (zebra fish)
library(org.Rn.eg.db) #Ratus norvegicus
#library(org.Mmu.eg.db) #Macaca mulata
library(chorddiag)
library(EnsDb.Mmusculus.v79)
library(EnsDb.Hsapiens.v86)
library(EnsDb.Rnorvegicus.v79)
library(limma)
library(tidyverse)
library(DT)
library(RColorBrewer)
library(purrr)
library(plotly)
library(ggpubr)
library(DESeq2)
library(fgsea)
library(shinyalert)
library(shinyBS)
library(shinyWidgets)
library(shinydashboardPlus)
library(pheatmap)
library(heatmaply)
library(shinyjs)
library(shinythemes)
library(rgl)
library(rglwidget)
library(scales)
library(stringr)
library(shinybusy)
library(visNetwork)
source("global.R")
source("utils.R")
options(shiny.maxRequestSize = 3000*1024^2)

### HEADER ############ 
header <- dashboardHeader(title = "Gene list enrichment and report", 
                          titleWidth = 300, 
                          dropdownMenuOutput("messageMenu"),
                          tags$li(class = "dropdown", actionButton("aboutButton", "About"),
                                  style="margin-top:8px; margin-right: 5px")
)
### SIDEBAR ##########
sidebar <- dashboardSidebar(useShinyalert(),
                            useShinyjs(),
                            sidebarMenu(
                              menuItem(
                              "App Information",
                              tabName = "info",
                              icon = icon("info")
                            )),
                            sidebarMenu(
                                menuItem(
                                    pickerInput(
                                        inputId = "specie",
                                        label = "Select specie",
                                        choices = list( "Human" = "Hs", "Mouse" = "Mm", "Ratus" = "Rn"),
                                        options = list(title = "specie"),
                                        selected = "Mm"
                                    ) 
                                ),
                                menuItem(
                                  pickerInput(
                                    inputId = "annotation",
                                    label = "Select annotation gene",
                                    choices = list("Ensembl" = "ensg", "Symbol"="symbol"),
                                    options = list(title="annotation"),
                                    selected = "ensg"
                                  )
                                ),
                                sidebarMenu("", sidebarMenuOutput("prevw")),
                                sidebarMenu("", sidebarMenuOutput("menuKegg")),
                                sidebarMenu("", sidebarMenuOutput("menuGO")),
                                sidebarMenu("", sidebarMenuOutput("menuGSEA"))
                            )
                            )

### BODY ###############
body <- dashboardBody(
      add_busy_gif(src="dna-mini.gif", position = "full-page", width = 10, height = 10 ),
     tags$head(
       tags$link(rel = "stylesheet", type = "text/css", href = "customDark.css")
     ),
    setShadow(class = "shiny-plot-output"),
    setShadow( class = "box"),
    setShadow( class = "svg-container"),
  bsAlert("alert"),
  tabItems(
    # Initial INFO
    tabItem(tabName = "info",
            fluidRow(column(width = 4,
              box(width=12, 
                  uiOutput(outputId = "geneList"), 
                  uiOutput(outputId = "geneFile"),
                  uiOutput(outputId = "geneButton")
                  )
              ),
            column(width = 8,
            box(width=12,
                status = "info",
                title = h1(strong("Welcome to Enrich app 2020!") ),
            h3("Before starting using the app"),
            p("As a necessary initial element to start the analysis, 
                the program imports an object of the type DeseqDataSet, 
                generated by the DESeq function of the", 
              a("DESeq2", href="https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"),
              "library. It has to be compress as an RDS object and upload 
                by clicking on the search engine button found in the upper left 
                corner of the app. Choose your object and enjoy your enrichment analysis ;)"),
            br(),
            h3("Get the app ready to use!"),
            p("First of all, select the specie of your experiment. 
              Then the option to enter your RDS object containing your 
              analysis will be unlocked. Upload it and wait for the loading 
              to be completed. When the loading symbol stops moving, 
              you can proceed to the next tab! "
              ),
            br(),
            p("Take advantage of every symbol of info" , icon("info-circle"), "that you might find.
              It can provide you with information that may be useful for 
              the proper functioning of the app. "
            ),
            br(),
            h3("How to download the app"),
            p("This app can be found on ",
              a("GitHub.", 
                href = "https://github.com/"))),
            )
            ), 
            br(),
        fluidRow(column(width = 6, offset = 3,
                    uiOutput("enrichbutton")
                    ))
    ),
    # preview tab
    tabItem(tabName = "preview",
            source(file = "ui-preview-tab.R",
            local=TRUE,
            encoding = "UTF-8"
            )$value),
    # kegg tab content
    tabItem(tabName = "kegg",
            source(file = "ui-kegg-tab.R",
                   local = TRUE,
                   encoding = "UTF-8"
                   )$value),
    # GO tab GO tab
    tabItem( tabName = "go",
             source(file = "ui-go-tab.R",
                    local = TRUE,
                    encoding = "UTF-8",
                    )$value),
    # GSEA tab
    tabItem( tabName = "gsea",
             source(file = "ui-gsea-tab.R",
                    local = TRUE,
                    encoding = "UTF-8",
                    )$value)
  ) # fin tab items
)# fin dashboardbody

########################################## UI #################################################

ui <- dashboardPage(title="Rnaseq viewer and report",
                    header,
                    sidebar,
                    body
) # fin del UI

########################################## SERVER #################################################
server <- function(input, output, session) {
  
    observeEvent(input$aboutButton, {
          shinyalert("Enrich app 2020", HTML("Authors:<br>
      Miriam Riquelme Pérez 
      <a href='https://www.linkedin.com/in/miriam-riquelme-perez/' target='_blank'> 
      <img src='linkedin_little.svg'> </a> <a href='mailto:miriam.riquelmep@gmail.com'>
      <img src='email.svg'></a><br>
      Fernando Pérez Sanz 
      <a href='https://www.linkedin.com/in/fernandoperez72/' target='_blank'> 
      <img src='linkedin_little.svg'> 
      </a> <a href='mailto:fernando.perez@ffis.es'> <img src='email.svg'></a><br>
      For any suggestion or bug, please contact us"),
                 imageUrl = "dna-svg-small-13.gif", 
                 imageWidth = 200, imageHeight = 100, html=TRUE)})
  
  # variables reactivas ######
  specie <- reactive({input$specie})
  annotation <- reactive({input$annotation})
  validatedGene <- reactiveValues(list=NULL)
  data <- reactiveValues(df=NULL)
  kgg <- reactiveValues(all=NULL)
  kggDT <- reactiveValues(all=NULL)
  go <- reactiveValues(all=NULL)
  goDT <- reactiveValues(all=NULL)
  gene <- reactiveValues(lost=NULL)
  gsea <- reactiveValues(gsea=NULL)
  df3cols <- reactiveValues(TF=FALSE)
  fc_switch <- reactive({input$fc_switch})
  logfcRange <- reactiveValues() # min y max logfc
  fcRange <- reactiveValues() # min y max fc
  numgenesDE <- reactiveValues(up=NULL, down=NULL)
  genesVolcano <- reactive({input$genesVolcano})
  genes <- reactiveValues()
  ## Leer data ##########################
  observeEvent(input$geneButton,{
    # comprobaciones listado manual
    if( !is.null(input$geneList)){
      if(input$geneList!="" ){
        if (annotation() == "ensg") {
          if (length(which(grepl("^ENS", input$geneList, ignore.case = TRUE))) <
              length(input$geneList)  ) {
            shinyalert("Oops!!", "One or more genes are not 
            in ENSEMBL format",
                       type = "error")
          } else{
            validatedGene$list <- validateGeneList(input$geneList, specie(), annotation() )
            data$df <- formatData( validatedGene$list, specie(), annotation() )
            lost <- which(is.na(data$df$ENTREZID))
            gene$lost <- data$df$ENSEMBL[lost]
            if(length(lost)!=0){ data$df <- data$df[-lost, ] }
            data$df$SYMBOL <- ifelse(is.na(data$df$SYMBOL), data$df$ENSEMBL, data$df$SYMBOL )
            }
        }
        if (annotation() == "symbol") {
          if (length(which(grepl("^ENS", input$geneList, ignore.case = TRUE))) ==  length(input$geneList) ) {
            shinyalert("Oops!!", "Looks like this entry is 
                       ENSEMBL please check your selection", 
                       type = "error")
          } else{
            validatedGene$list <- validateGeneList(input$geneList, specie(), annotation() )
            data$df <- formatData( validatedGene$list, specie(), annotation() )
            lost <- which(is.na(data$df$ENTREZID))
            gene$lost <- data$df$SYMBOL[lost]
            if(length(lost)!=0){ data$df <- data$df[-lost, ] }
          }
          }
        }
      }
    ## comprobaciones cargar fichero
    if(!is.null(input$geneFile$datapath)){
      if(input$geneFile$datapath != "" ){
        validatedGene$list <- as.data.frame( readxl::read_xlsx(input$geneFile$datapath, sheet = 1))
        if (annotation() == "ensg") {
          if(length(which(grepl("^ENS", validatedGene$list[,1], ignore.case = TRUE))) < nrow(validatedGene$list) ) {
            shinyalert("Oops!!", "One or more genes are not 
            in ENSEMBL format",
                       type = "error")
          } else{
                data$df <- formatData( validatedGene$list, specie(), annotation() )
                lost <- which(is.na(data$df$ENTREZID))
                gene$lost <- data$df$ENSEMBL[lost]
                if(length(lost)!=0){ data$df <- data$df[-lost, ] }
                data$df$SYMBOL <- ifelse(is.na(data$df$SYMBOL), data$df$ENSEMBL, data$df$SYMBOL )
          }
        }
        if (annotation() == "symbol") {
          if (length(which(grepl("^ENS", validatedGene$list[,1], ignore.case = TRUE))) ==  nrow(validatedGene$list)) {
            shinyalert("Oops!!", "Looks like this entry is 
                       ENSEMBL please check your selection", 
                       type = "error")
          } else{
                data$df <- formatData( validatedGene$list, specie(), annotation() )
                lost <- which(is.na(data$df$ENTREZID))
                gene$lost <- data$df$SYMBOL[lost]
                if(length(lost)!=0){ data$df <- data$df[-lost, ] }
          }
        }
      }
    }
    if( dim(data$df)[2]==5 ){
      df3cols$TF <- TRUE
    }
    logfcRange$min <- min(data$df$logFC)
    logfcRange$max <- max(data$df$logFC)
    fcRange$min <- ifelse(logfcRange$min<0, -(2^abs(logfcRange$min)), 2^abs(logfcRange$min))
    fcRange$max <- ifelse(logfcRange$max<0, -(2^abs(logfcRange$max)), 2^abs(logfcRange$max))
  })
  
  #TODO: Definir qué hacer con los NAs, eliminar, reportar, etc
  ## Pulsar Enrich Button ################################################
  observeEvent(input$enrichButton,{
    if( dim(data$df)[2]==3 ){
      kgg$all <- customKegg(data$df[,c("SYMBOL","ENTREZID") ], species = specie() )
      kggDT$all <- kegg2DT(kgg$all, data$df[,c("SYMBOL","ENTREZID") ] )
      go$all <- customGO(data$df[,c("SYMBOL","ENTREZID") ], species = "Mm")
      goDT$all <- go2DT(enrichdf = go$up, data = data$df[,c("SYMBOL","ENTREZID") ] )
    }
    if( dim(data$df)[2]==5 ){
      genes$Up <- data$df[data$df$logFC >= logfc()[2] & data$df$pval <= padj(),
                          c("SYMBOL","ENTREZID")]
      
      genes$Down <- data$df[data$df$logFC <= logfc()[1] & data$df$pval <= padj(),
                          c("SYMBOL","ENTREZID")]
      
      genes$all <- rbind(genes$Up, genes$Down)
      
      kgg$all <- customKegg(genes$all, species = specie() ) #"Mm"), species.KEGG = "mmu")
      kggDT$all <- kegg2DT(kgg$all, genes$all)
      
      kgg$up <- customKegg(genes$Up, species = specie() ) #"Mm")#, species.KEGG = "mmu")
      kggDT$up <- kegg2DT(kgg$up, genes$Up)
      
      kgg$down <- customKegg(genes$Down, species = specie() ) # "Mm")#, species.KEGG = "mmu")
      kggDT$down <- kegg2DT(kgg$down, genes$Down)
      
      go$all <- customGO(genes$all, species = "Mm")
      goDT$all <- go2DT(enrichdf = go$all, data = genes$all )
      
      go$up <- customGO(genes$Up, species = "Mm")
      goDT$up <- go2DT(enrichdf = go$up, data = genes$Up )
      
      go$down <- customGO(genes$Down, species = "Mm")
      goDT$down <- go2DT(enrichdf = go$down, data = genes$Down )
      kgg$up <- customKegg(data$df[,c("SYMBOL","ENTREZID") ], species = specie() )
      kggDT$up <- kegg2DT(kgg$up, data$df[,c("SYMBOL","ENTREZID") ] )
      go$up <- customGO(data$df[,c("SYMBOL","ENTREZID") ], species = "Mm")
      goDT$up <- go2DT(enrichdf = go$up, data = data$df[,c("SYMBOL","ENTREZID") ] )
      gsea$gsea <- gseaKegg(data$df[, c("ENTREZID","logFC")], specie() )
    }
  })
  
  ## Cosas a renderizar en preview si dflist 3 columns ##################
  ## sidebar menu preview ###################
  output$prevw <- renderMenu({
      validate(need(isTRUE(df3cols$TF), ""))
      sidebarMenu(
          menuItem(
              "Preview",
              tabName = "preview",
              icon = icon("chart-bar")
          )
          )
          })
  
  ## Gene List ####################
  output$geneList <- renderUI({
    validate(need(specie(),""))
    validate(need(annotation(),""))
    textAreaInput(inputId = "geneList", label = "Input simple gene list ...", resize = "vertical")
  })
  
  ## Gene File #####################
  output$geneFile <- renderUI({
    validate(need(specie(),""))
    validate(need(annotation(),""))
    fileInput(inputId = "geneFile", label="...or upload file with gene list")
  })
  ## Boton validar ###############
  output$geneButton <- renderUI({
    validate(need(specie(),""))
    validate(need(annotation(),""))
    actionButton("geneButton", label = "Click to validate data")
  })
  ## boton enrich #########################
  output$enrichbutton <- renderUI({
    validate(need(data$df, ""))
    validate(need(!isTRUE(df3cols$TF), ""))
    actionBttn("enrichButton", label = "Click to run enrichment", size="lg", color="default", icon = icon("images"))
  })
  

## sidebar menu kegg ###################
  output$menuKegg <- renderMenu({
      validate(need(kgg$up, ""))
      sidebarMenu(
          menuItem(
              "Kegg Enrichment",
              tabName = "kegg",
              icon = icon("chart-bar")
          )
          )
          })
  
    # Acciones al pulsar applyButton ################
  padjVal <- reactiveValues(val=0.05)
  fcVal <- reactiveValues( val=c(-1.5, 1.5) )
  logfcVal <- reactiveValues(val=c(-0.5,0.5))
  padj <- reactive({padjVal$val})
  logfc <- reactive({logfcVal$val})
  fc <- reactive({fcVal$val})
  
  observeEvent(input$applyParam,{
      padjVal$val <- input$padj
      if( isTRUE( fc_switch()) ){
        logfcTmp <- vector()
        fcVal$val <-input$fc
        logfcTmp[1] <- ifelse(fc()[1]<0, -log2(abs(fc()[1])), log2(abs(fc()[1])) )
        logfcTmp[2] <- ifelse(fc()[2]<0, -log2(abs(fc()[2])), log2(abs(fc()[2])) )
      } else {
        logfcTmp <- input$logfc
      }
      if(logfcTmp[1]==logfcTmp[2]){
          logfcVal$val <- c(0,0)
          }else{
            logfcVal$val <- logfcTmp
          }
    })
  
      
  ## side menubar GO #########################
      output$menuGO <- renderMenu({
      validate(need(go$up,""))
      sidebarMenu(  
        menuItem(
              "GO Enrichment",
              tabName = "go",
              icon = icon("chart-bar")
          )
        )
      })
  ## sidebar menu GSEA #####################333
  output$menuGSEA <- renderMenu({
      validate(need(gsea$gsea,""))
      sidebarMenu(  
          menuItem("GSEA",
                   tabName = "gsea",
                   icon = icon("chart-line"))
        )
      })
    # ui selector de genes para volcano plot #######################
  output$geneSelector <- renderUI({
    validate(need(data$df, ""))
    genes <- as.character(data$df$GeneName_Symbol[ which(!( data$df$pval>padj() &
                                                             data$df$logFC>logfc()[1] &
                                                             data$df$logFC<logfc()[2] )) ])
    selectInput("genesVolcano", label="Select gene[s] to label",
                choices = genes,
                multiple = TRUE)
  })
  
  # Deslizador fc/logfc según switch #################
  output$fc_control <- renderUI({
    if(isTRUE(fc_switch())){
      validate(need(data$df, ""))
      valmin <- ifelse(input$logfc[1]<0, -2^(abs(input$logfc[1] )), 2^(abs(input$logfc[1])) )
      valmax <- ifelse(input$logfc[2]<0, -2^(abs(input$logfc[2] )), 2^(abs(input$logfc[2])) )
      sliderInput("fc", label = "Select FC range to remove (keeps the tails)",
                  min=round(fcRange$min,3), max=round(fcRange$max, 3),
                  value = c(valmin, valmax), step = 0.1 )
    } else {
      validate(need(data$df, ""))
      validate(need(fc(), ""))
        if(is.null(input$fc[1]) ){
          valmin = -0.5
          valmax = 0.5
        } else{
          valmin <- ifelse(input$fc[1]<0, -log2(abs(input$fc[1] )), log2(abs(input$fc[1])) )
          valmax <- ifelse(input$fc[2]<0, -log2(abs(input$fc[2] )), log2(abs(input$fc[2])) )
      }
      sliderInput("logfc", label = "Select logFC range to remove (keeps the tails)",
                min=round(logfcRange$min,3), max=round(logfcRange$max, 3),
                value = c(valmin, valmax), 
                step = 0.1 )
    }
  })
    # ui selector padj #################################
  output$padj <- renderUI({
    validate(need(data$df,""))
    sliderInput("padj", label = "Select p-adjusted threshold", min = 0, max=0.2,
                value=0.05, step = 0.005 )
  })
  
    # infoboxes ###############################
  output$allbox <- renderInfoBox({
      validate(need(data$df, ""))
      validate(need(padj(), ""))
      validate(need(logfc(), ""))
      numall <- nrow( data$df[ ((data$df$logFC >= logfc()[2] |
                                    data$df$logFC< logfc()[1]) &
                                   data$df$pval <= padj() ),] ) 
      infoBox("All DE genes", numall, icon = icon("arrows-alt-v"), color = "light-blue", fill = TRUE)
  })
  output$upbox <- renderInfoBox({
      validate(need(data$df, ""))
      validate(need(padj(), ""))
      validate(need(logfc(), ""))
      numup <- nrow( data$df[(data$df$logFC >= logfc()[2]) & (data$df$pval <= padj()), ]) 
      numgenesDE$up <- numup
      infoBox("Upregulated genes", numup, icon = icon("thumbs-up", lib = "glyphicon"), color = "light-blue", fill=TRUE)
  })
  output$downbox <- renderInfoBox({
      validate(need(data$df, ""))
      validate(need(padj(), ""))
      validate(need(logfc(), ""))
      numdown <- nrow( data$df[(data$df$logFC <= logfc()[1]) & (data$df$pval <= padj()), ])
      numgenesDE$down <- numdown
      infoBox("Downregulated genes", numdown, icon = icon("thumbs-down", lib = "glyphicon"), color = "light-blue", fill=TRUE)
  })
  
  output$fcdown <- renderUI({
        validate(need(logfcRange$min, ""))
        validate(need(logfc(),""))
        initMin <- round( logfcRange$min, 2)
        initMax <- round( logfcRange$max, 2)
        if(logfc()[1]>=0){
            fgColor="#6baed6"
            inputColor="white"
            bgColor ="#46505a"
            rotation="clockwise"
            min=0
            max=initMax
            angleOffset = 0
        }else{
            fgColor="#46505a"
            inputColor="white"
            bgColor ="#e6550d"
            rotation="clockwise"
            min=initMin
            max=0
            angleOffset=180
        }
      knobInput(
          inputId = "myKnobdown",
          label = "Lower logFC cutoff",
          value = round(logfc()[1],2),
          min = min,
          max=max,
          rotation=rotation,
          displayPrevious = TRUE,
          fgColor = fgColor,
          inputColor = inputColor,
          bgColor = bgColor,
          #angleArc = 180,
          #angleOffset = angleOffset,
          width = "80%",
          height = "80%"
      )
  })
  output$fcup <- renderUI({
        validate(need(logfcRange$min, ""))
        validate(need(logfc(),""))
        initMin <- round( logfcRange$min, 2)
        initMax <- round( logfcRange$max, 2)
        if(logfc()[2]>=0){
            fgColor="#6baed6"
            inputColor="white"
            bgColor ="#46505a" 
            rotation="clockwise"
            min=0
            max=initMax
            angleOffset = 0
        }else{
            fgColor="#46505a"
            inputColor="white"
            bgColor ="#e6550d"
            rotation="clockwise"
            min=initMin
            max=0
            angleOffset=180
        }
      knobInput(
          inputId = "myKnobup",
          label = "Upper LogFC cutoff",
          value = round(logfc()[2], 2),
          min = min,
          max=max,
          rotation=rotation,
          displayPrevious = TRUE,
          fgColor = fgColor,
          inputColor = inputColor,
          bgColor = bgColor,
          #angleArc = 180,
          #angleOffset = angleOffset,
          width = "80%",
          height = "80%"
      )
  })
  output$pval <- renderUI({
      validate(need(padj(), ""))
      fgColor = "#74c476"
      inputColor = "white"
      bgColor = "#46505a"
      knobInput(
          inputId = "myKnobpval",
          label = "P.adj cutoff",
          value = round(padj(), 2),
          min = 0,
          max = 0.2,
          rotation = "clockwise",
          displayPrevious = TRUE,
          fgColor = fgColor,
          inputColor = inputColor,
          bgColor = bgColor,
          #angleArc = 180,
          #angleOffset = 90,
          width = "80%",
          height = "80%"
      )
  })
# ....................... ####
  # volcano plot #########
  output$volcano <- renderPlot( {
    #validate(need(datos$dds, "Load file and condition to render Volcano"))
    validate(need(data$df, "Load file to render plot"))
    res <-  data$df
    #res$`-log10padj` <- (-log10(res$padj)) 
    CustomVolcano(res, lab = as.character(res$SYMBOL),
                  selectLab = genesVolcano(),
                    x = 'logFC',
                    y = 'pval',
                    pCutoff = padj(),
                    FCcutoffUP = logfc()[2],
                    FCcutoffDOWN = logfc()[1],
                    xlim = c(-8, 8),
                    col = c("gray", "#7cccc3", "#d99c01", input$upColor, input$downColor))
    })

xy <- reactive({
  res <- data$df
  res$`-log10padj` <- (-log10(res$pval)) 
  nearPoints(res, input$plot_click1, xvar = "logFC", yvar = "-log10padj")
})
output$texto1 <- renderTable( digits = -2, {
        xy <- xy()
        xy[,c(2,4,5,6)]
    })
# ....................... ####
## karyoplot ######################################
output$karyoPlot <- renderPlot({
    validate(need(data$df, "Load file to render plot"))
    krtp(data$df, specie = specie(), pval = padj(), fcdown = logfc()[1],
         fcup = logfc()[2], bg="#46505a", coldown="#4ADBFF" , colup="#f7665c")
})
# .......................####
  # variables KEGG ALL ##########################
  rowsAll <- reactive({input$tableAll_rows_selected})
 # KEGG table all #####################################
  output$tableAll <- DT::renderDT(server=TRUE,{
    validate(need(kgg$all, "Load file to render table"))
    names(kggDT$all)[names(kggDT$all) == "DE"] <- "DEG"
    names(kggDT$all)[names(kggDT$all) == "P.DE"] <- "p-value"
    tituloTabla <- paste0("Table: Kegg DEG genes")
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "kegg",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "kegg",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(
      kggDT$all,
      vars = c("genes"),
      filter = list(position="top", clear=FALSE),
      escape = FALSE,
      opts = list(order = list(list(5, 'asc')),
        pageLength = 10, white_space = "normal",
        buttons = customButtons))
  }) 
  # KEGG barplot all################
  output$keggPlot <- renderPlotly ({
    validate(need(kgg$all, "Load file to render BarPlot"))
    rowsAll <- rowsAll()
    if(is.null(rowsAll)){
        if( dim(kgg$all)[1]<10 ){rowsUp <-  seq_len(nrow(kgg$all)) }
        else{ rowsAll <-  seq_len(10)  }
        }
    plotKegg(enrichdf = kgg$all[rowsAll,], nrows = length(rowsAll), colors = c(input$allColor))
  })
  # KEGG chordiag plot all ###############
  output$keggChord <- renderChorddiag({
    validate(need(kgg$all, "Load file to render ChordPlot"))
    rowsAll<- rowsAll()
    if(is.null(rowsAll)){
        if( dim(kgg$all)[1]<10 ){rowsAll <-  seq_len(nrow(kgg$all)) }
        else{ rowsAll <-  seq_len(10)  }
        }
    chordPlot(kgg$all[rowsAll, ], nRows = length(rowsAll), orderby = "P.DE")
  })
 output$legendChorAll <- renderPlot({
    validate(need(kgg$all, "Load file to render ChordPlot"))
    rowsAll <- rowsAll()
    if(is.null(rowsAll)){
        if (dim(kgg$all)[1] < 10) {rowsAll <-  seq_len(nrow(kgg$all))}
        else{rowsAll <-  seq_len(10)}
        
        }
    legendChorplot(kgg$all[rowsAll, ] )
  })
  # KEGG dotplot UP ################### 
  output$keggDotAll <- renderPlot({
    validate(need(kgg$all, "Load file and select to render dotPlot"))
    validate(need(rowsAll(), "Select the paths of interest to render DotPlot"))
    rowsAll <- rowsAll()
    if(is.null(rowsAll)){rowsAll <- c(1:20)}
    dotPlotkegg(kgg$all[rowsAll,], n = length(rowsAll))
  })
  # KEGG heatmap All #################
  output$heatmapKeggAll <- renderPlotly({
    validate(need(kgg$all, "Load file and select to render Heatmap"))
    validate(need(rowsAll(), "Select the paths of interest to render HeatMap"))
    validate(need(kggDT$all, ""))
    heatmapKegg(kggDT$all, rowsAll())
  })
 
# KEGG cnet All #################
  output$legend <- renderPlot({
    validate(need(kgg$all, "Load file and select to render Net Plot"))
    validate(need(rowsAll(), "Select the paths of interest to render NetPlot"))
    validate(need(kggDT$all, ""))
    visnetLegend(kggDT = kggDT$all , rows = rowsAll() )
  })
   output$keggNet <- renderUI({
    if(!isTRUE( input$keggNet_switch ) ){
      plotOutput("cnetKegg", height = "600px")
    } else{
      visNetworkOutput("visnetKegg", height = "600px")
    }
  })
  output$cnetKegg <- renderPlot({
    validate(need(kgg$all, "Load file and select to render Net Plot"))
    validate(need(rowsAll(), "Select the paths of interest to render NetPlot"))
    customCnetKegg(kgg$all, rowsAll(), genesAll = data$df, genesDown = NULL)
  })
  output$visnetKegg <- renderVisNetwork({
    validate(need(kgg$all, "Load file and select to render Net Plot"))
    validate(need(rowsAll(), "Select the paths of interest to render NetPlot"))
    validate(need(kggDT$all, ""))
    visData <- customVisNet(kgg$all, nTerm=rowsAll(), kggDT$all,
                             up = genes$Up$SYMBOL, down = genes$Down$SYMBOL )
    visNetwork(visData$nodes, visData$edges, background = "#ffffff") %>%
    visOptions(highlightNearest = list(enabled=TRUE, hover=TRUE),
                nodesIdSelection = TRUE)
  })

# ....................... ####
  # variables KEGG UP ##########################
  rowsUp <- reactive({input$table_rows_selected})
 # KEGG table up #####################################
  output$table <- DT::renderDT(server=TRUE,{
    validate(need(kgg$up, "Load file to render table"))
    names(kggDT$up)[names(kggDT$up) == "DE"] <- "DEG"
    names(kggDT$up)[names(kggDT$up) == "P.DE"] <- "p-value"
    tituloTabla <- paste0("Table: Kegg DEG genes")
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "kegg",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "kegg",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(
      kggDT$up,
      vars = c("genes"),
      filter = list(position="top", clear=FALSE),
      escape = FALSE,
      opts = list(order = list(list(5, 'asc')),
        pageLength = 10, white_space = "normal",
        buttons = customButtons))
  }) 
  # KEGG barplot up################
  output$keggPlot <- renderPlotly ({
    validate(need(kgg$up, "Load file to render BarPlot"))
    rowsUp <- rowsUp()
    if(is.null(rowsUp)){
        if( dim(kgg$up)[1]<10 ){rowsUp <-  seq_len(nrow(kgg$up)) }
        else{ rowsUp <-  seq_len(10)  }
        }
    plotKegg(enrichdf = kgg$up[rowsUp,], nrows = length(rowsUp), colors = c(input$upColor))
  })
  # KEGG chordiag plot up ###############
  output$keggChord <- renderChorddiag({
    validate(need(kgg$up, "Load file to render ChordPlot"))
    rowsUp<- rowsUp()
    if(is.null(rowsUp)){
        if( dim(kgg$up)[1]<10 ){rowsUp <-  seq_len(nrow(kgg$up)) }
        else{ rowsUp <-  seq_len(10)  }
        }
    chordPlot(kgg$up[rowsUp, ], nRows = length(rowsUp), orderby = "P.DE")
  })
 output$legendChorUp <- renderPlot({
    validate(need(kgg$up, "Load file to render ChordPlot"))
    rowsUp <- rowsUp()
    if(is.null(rowsUp)){
        if (dim(kgg$up)[1] < 10) {rowsUp <-  seq_len(nrow(kgg$up))}
        else{rowsUp <-  seq_len(10)}
        
        }
    legendChorplot(kgg$up[rowsUp, ] )
  })
  # KEGG dotplot UP ################### 
  output$keggDotUp <- renderPlot({
    validate(need(kgg$up, "Load file and select to render dotPlot"))
    validate(need(rowsUp(), "Select the paths of interest to render DotPlot"))
    rowsUp <- rowsUp()
    if(is.null(rowsUp)){rowsUp <- c(1:20)}
    dotPlotkegg(kgg$up[rowsUp,], n = length(rowsUp))
  })
  # KEGG heatmap Up #################
  output$heatmapKeggUp <- renderPlotly({
    validate(need(kgg$up, "Load file and select to render Heatmap"))
    validate(need(rowsUp(), "Select the paths of interest to render HeatMap"))
    validate(need(kggDT$up, ""))
    heatmapKegg(kggDT$up, rowsUp())
  })
 
# KEGG cnet Up #################
  output$legend <- renderPlot({
    validate(need(kgg$up, "Load file and select to render Net Plot"))
    validate(need(rowsUp(), "Select the paths of interest to render NetPlot"))
    validate(need(kggDT$up, ""))
    visnetLegend(kggDT = kggDT$up , rows = rowsUp() )
  })
   output$keggNet <- renderUI({
    if(!isTRUE( input$keggNet_switch ) ){
      plotOutput("cnetKegg", height = "600px")
    } else{
      visNetworkOutput("visnetKegg", height = "600px")
    }
  })
  output$cnetKegg <- renderPlot({
    validate(need(kgg$up, "Load file and select to render Net Plot"))
    validate(need(rowsUp(), "Select the paths of interest to render NetPlot"))
    customCnetKegg(kgg$up, rowsUp(), genesUp = data$df, genesDown = NULL)
  })
  output$visnetKegg <- renderVisNetwork({
    validate(need(kgg$up, "Load file and select to render Net Plot"))
    validate(need(rowsUp(), "Select the paths of interest to render NetPlot"))
    validate(need(kggDT$up, ""))
    visData <- customVisNet(kgg$up, nTerm=rowsUp(), kggDT$up,
                             up = genes$Up$SYMBOL, down = NULL )
    visNetwork(visData$nodes, visData$edges, background = "#ffffff") %>%
    visOptions(highlightNearest = list(enabled=TRUE, hover=TRUE),
                nodesIdSelection = TRUE)
  })
  # ....................... ####
  # variables KEGG Down ##########################
  rowsDown <- reactive({input$table_rows_selected})
 # KEGG table down #####################################
  output$table <- DT::renderDT(server=TRUE,{
    validate(need(kgg$down, "Load file to render table"))
    names(kggDT$down)[names(kggDT$down) == "DE"] <- "DEG"
    names(kggDT$down)[names(kggDT$down) == "P.DE"] <- "p-value"
    tituloTabla <- paste0("Table: Kegg DEG genes")
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "kegg",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "kegg",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(
      kggDT$down,
      vars = c("genes"),
      filter = list(position="top", clear=FALSE),
      escape = FALSE,
      opts = list(order = list(list(5, 'asc')),
        pageLength = 10, white_space = "normal",
        buttons = customButtons))
  }) 
  # KEGG barplot down################
  output$keggPlot <- renderPlotly ({
    validate(need(kgg$down, "Load file to render BarPlot"))
    rowsDown <- rowsDown()
    if(is.null(rowsDown)){
        if( dim(kgg$down)[1]<10 ){rowsDown <-  seq_len(nrow(kgg$down)) }
        else{ rowsDown <-  seq_len(10)  }
        }
    plotKegg(enrichdf = kgg$down[rowsDown,], nrows = length(rowsDown), colors = c(input$downColor))
  })
  # KEGG chordiag plot down ###############
  output$keggChord <- renderChorddiag({
    validate(need(kgg$down, "Load file to render ChordPlot"))
    rowsDown<- rowsDown()
    if(is.null(rowsDown)){
        if( dim(kgg$down)[1]<10 ){rowsDown <-  seq_len(nrow(kgg$down)) }
        else{ rowsDown <-  seq_len(10)  }
        }
    chordPlot(kgg$down[rowsDown, ], nRows = length(rowsDown), orderby = "P.DE")
  })
 output$legendChorDown <- renderPlot({
    validate(need(kgg$down, "Load file to render ChordPlot"))
    rowsDown <- rowsDown()
    if(is.null(rowsDown)){
        if (dim(kgg$down)[1] < 10) {rowsDown <-  seq_len(nrow(kgg$down))}
        else{rowsDown <-  seq_len(10)}
        
        }
    legendChorplot(kgg$down[rowsDown, ] )
  })
  # KEGG dotplot UP ################### 
  output$keggDotDown <- renderPlot({
    validate(need(kgg$down, "Load file and select to render dotPlot"))
    validate(need(rowsDown(), "Select the paths of interest to render DotPlot"))
    rowsDown <- rowsDown()
    if(is.null(rowsDown)){rowsDown <- c(1:20)}
    dotPlotkegg(kgg$down[rowsDown,], n = length(rowsDown))
  })
  # KEGG heatmap Down #################
  output$heatmapKeggDown <- renderPlotly({
    validate(need(kgg$down, "Load file and select to render Heatmap"))
    validate(need(rowsDown(), "Select the paths of interest to render HeatMap"))
    validate(need(kggDT$down, ""))
    heatmapKegg(kggDT$down, rowsDown())
  })
 
# KEGG cnet Down #################
  output$legend <- renderPlot({
    validate(need(kgg$down, "Load file and select to render Net Plot"))
    validate(need(rowsDown(), "Select the paths of interest to render NetPlot"))
    validate(need(kggDT$down, ""))
    visnetLegend(kggDT = kggDT$down , rows = rowsDown() )
  })
   output$keggNet <- renderUI({
    if(!isTRUE( input$keggNet_switch ) ){
      plotOutput("cnetKegg", height = "600px")
    } else{
      visNetworkOutput("visnetKegg", height = "600px")
    }
  })
  output$cnetKegg <- renderPlot({
    validate(need(kgg$down, "Load file and select to render Net Plot"))
    validate(need(rowsDown(), "Select the paths of interest to render NetPlot"))
    customCnetKegg(kgg$down, rowsDown(), genesDown = data$df, genesDown = NULL)
  })
  output$visnetKegg <- renderVisNetwork({
    validate(need(kgg$down, "Load file and select to render Net Plot"))
    validate(need(rowsDown(), "Select the paths of interest to render NetPlot"))
    validate(need(kggDT$down, ""))
    visData <- customVisNet(kgg$down, nTerm=rowsDown(), kggDT$down,
                             down = genes$Down$SYMBOL, up = NULL )
    visNetwork(visData$nodes, visData$edges, background = "#ffffff") %>%
    visOptions(highlightNearest = list(enabled=TRUE, hover=TRUE),
                nodesIdSelection = TRUE)
  })
 # ....................... ####
 # variable GO ###################################
    bprowsup <- reactive({input$tableBP_rows_selected})
    mfrowsup <- reactive({input$tableMF_rows_selected})
    ccrowsup <- reactive({input$tableCC_rows_selected})
  
 # GO table BP UP#####################
  output$tableBP <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-BP DEG genes")
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "BPup",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "BPup",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="BP",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons))
  })
  # GO plots BP UP #####################
  output$plotBP <- renderPlotly({
    validate(need(go$up, "Load file to render plot"))
    bprowsup <- bprowsup()
    if(is.null(bprowsup)){bprowsup <- c(1:10)}
    gosBP <- go$up[go$up$Ont=="BP",]
    plotGO(enrichdf = gosBP[bprowsup, ], nrows = length(bprowsup), ont="BP",
           colors = c(input$upColor) )
  })
  # GO BP dotplot up ################### 
  output$BPDotUp <- renderPlotly({
    validate(need(go$up, "Load file to render dotPlot"))
    validate(need(bprowsup(), "Select the terms of interest to render DotPlot"))
    bprowsup <- bprowsup()
    if(is.null(bprowsup)){bprowsup <- c(1:20)}
    gosBP <- go$up[go$up$Ont=="BP",]
    dotPlotGO(gosBP[bprowsup,], n = length(bprowsup))
  })
  # GO table MF UP #####################
  output$tableMF <- DT::renderDataTable({
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-MF DEG genes")
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "MFup",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "MFup",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="MF",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons,
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots MF UP #####################
  output$plotMF <- renderPlotly({
    validate(need(go$up, "Load file to render plot"))
    mfrowsup <- mfrowsup()
    if(is.null(mfrowsup)){mfrowsup <- c(1:10)}
    gosMF <- go$up[go$up$Ont=="MF",]
    plotGO(enrichdf = gosMF[mfrowsup, ], nrows = length(mfrowsup), ont = "MF",
           colors = c(input$upColor) )
  })
  # GO MF dotplot up ################### 
  output$MFDotUp <- renderPlotly({
    validate(need(go$up, "Load file to render dotPlot"))
    validate(need(mfrowsup(), "Select the terms of interest to render DotPlot"))
    mfrowsup <- mfrowsup()
    if(is.null(mfrowsup)){mfrowsup <- c(1:20)}
    gosMF <- go$up[go$up$Ont=="MF",]
    dotPlotGO(gosMF[mfrowsup,], n = length(mfrowsup))
  })
  # GO table CC UP #####################
  output$tableCC <- DT::renderDataTable(server=TRUE,{
    validate(need(goDT$up, "Load file to render table"))
    goDT <- goDT$up
    names(goDT)[names(goDT) == "DE"] <- "DEG"
    names(goDT)[names(goDT) == "P.DE"] <- "p-value"
    names(goDT)[names(goDT) == "level"] <- "Ont.level"
    goDT$Ont.level = as.integer(goDT$Ont.level)
    tituloTabla <- paste0("Table: GO-CC DEG genes")
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "CCup",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "CCup",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    datatable2(goDT[goDT$Ont=="CC",], vars = c("genes"),
               filter = list(position="top", clear=FALSE),
               escape = FALSE,
               opts = list(order = list(list(6, 'asc')),
                           pageLength = 10, white_space = "normal",
                           buttons = customButtons,
                           ajax = list(serverSide = TRUE, processing = TRUE))
    )
  })
  # GO plots CC UP #####################
  output$plotCC <- renderPlotly({
    validate(need(go$up, "Load file to render plot"))
    ccrowsup <- ccrowsup()
    if(is.null(ccrowsup)){ccrowsup <- c(1:10)}
    gosCC <- go$up[go$up$Ont=="CC",]
    plotGO(enrichdf = gosCC[ccrowsup,], nrows = length(ccrowsup), ont="CC",
           colors = c(input$upColor))
  })
  # GO CC dotplot up ################### 
  output$CCDotUp <- renderPlotly({
    validate(need(go$up, "Load file to render dotPlot"))
    validate(need(ccrowsup(), "Select the terms of interest to render DotPlot"))
    ccrowsup <- ccrowsup()
    if(is.null(ccrowsup)){ccrowsup <- c(1:20)}
    gosCC <- go$up[go$up$Ont=="CC",]
    dotPlotGO(gosCC[ccrowsup,], n = length(ccrowsup))
  })
# ....................... ####
  ## variable GSEA #############
    gsearow <- reactive({input$gseaTable_rows_selected})
   
  # GSEA table ##########################
  output$gseaTable <- renderDataTable({
    validate(need(gsea$gsea, "Load file to render table"))
    mygsea <- gsea$gsea
    if( length(which(mygsea@result$p.adjust<=0.05)) == 0 ){
        createAlert(session, anchorId = "gsea", title = "Oops!!", 
          content = "Sorry, I didn't get any significant results for this analysis",
          append=FALSE, style = "info")
    } else{
    table <- mygsea@result[mygsea@result$p.adjust<=0.05 ,2:9] %>% 
      mutate_at(vars(3:7), ~round(., 4))

    tituloTabla <- paste0("Table: GSEA pathway")
    customButtons <- list(
        list(extend = "copy", title=tituloTabla),
        list(extend = "excel",
            filename = "GSEAkegg",
            title = tituloTabla),
        list(extend = "pdf",
            filename = "GSEAkegg",
            title = tituloTabla),
        list(extend = "print", title=tituloTabla)
    )
    DT::datatable( table,
                   rownames=FALSE,
                   filter = list(position="top", clear=FALSE),
                   options = list(order = list(list(4, 'asc')),
                     lengthMenu = list(c(10,25,50,100,-1), c(10,25,50,100,"All")),
                     columnDefs = list(list(orderable = FALSE,
                                            className = "details-control",
                                            targets = 1)
                     ),
                     dom = "Bfrtipl",
                     buttons = customButtons,
                     list(pageLength = 10, white_space = "normal")
                   )
    )
    }
  })
  # GSEA plot ##########################
  output$gseaPlot <- renderPlot({
    validate(need(gsea$gsea, "Load file to render table"))
    gseanr <- gsearow()
    if(is.null(gseanr)){gseanr <- c(1)}
    mygsea <- gsea$gsea
    if( length(which(mygsea@result$p.adjust<=0.05)) == 0 ){
        createAlert(session, anchorId = "gseaPlot", title = "Oops!!", 
          content = "Sorry, I didn't get any significant results for this analysis",
          append=FALSE, style = "info")
    } else{
        enrichplot::gseaplot2(gsea$gsea, geneSetID = gseanr, pvalue_table = TRUE, ES_geom = "line")
        }
  })
}



shinyApp(ui, server)