library(shinydashboard)
library(AnnotationDbi)
library(org.Mm.eg.db) #Mus musculus
library(org.Hs.eg.db) #Homo sapiens
#library(org.Dr.eg.db) #Danio rerio (zebra fish)
library(org.Rn.eg.db) #Ratus norvegicus
#library(org.Mmu.eg.db) #Macaca mulata
library(chorddiag)
library(EnsDb.Mmusculus.v79)
library(EnsDb.Hsapiens.v86)
library(EnsDb.Rnorvegicus.v79)
library(limma)
library(tidyverse)
library(DT)
library(RColorBrewer)
library(purrr)
library(plotly)
library(ggpubr)
library(DESeq2)
library(fgsea)
library(shinyalert)
library(shinyBS)
library(shinyWidgets)
library(shinydashboardPlus)
library(pheatmap)
library(heatmaply)
library(shinyjs)
library(shinythemes)
library(rgl)
library(rglwidget)
library(scales)
library(stringr)
library(shinybusy)
source("utils.R")
options(shiny.maxRequestSize = 3000*1024^2)

### HEADER ############ 
header <- dashboardHeader(title = "Gene list enrichment and report", 
                          titleWidth = 300, 
                          dropdownMenuOutput("messageMenu"),
                          tags$li(class = "dropdown", actionButton("aboutButton", "About"),
                                  style="margin-top:8px; margin-right: 5px")
)
### SIDEBAR ##########
sidebar <- dashboardSidebar(useShinyalert(),
                            useShinyjs(),
                            sidebarMenu(
                              menuItem(
                              "App Information",
                              tabName = "info",
                              icon = icon("info")
                            )),
                            sidebarMenu(
                                menuItem(
                                    pickerInput(
                                        inputId = "specie",
                                        label = "Select specie",
                                        choices = list( "Human" = "Hs", "Mouse" = "Mm", "Ratus" = "Rn"),
                                        options = list(title = "specie"),
                                        selected = NULL
                                    ) 
                                ),
                                menuItem(
                                  pickerInput(
                                    inputId = "annotation",
                                    label = "Select annotation gene",
                                    choices = list("Ensembl" = "ensg", "Symbol"="symbol"),
                                    options = list(title="annotation"),
                                    selected = NULL
                                  )
                                )
                            )
                            )

### BODY ###############
body <- dashboardBody(
      add_busy_gif(src="dna-mini.gif", position = "full-page", width = 10, height = 10 ),
     tags$head(
       tags$link(rel = "stylesheet", type = "text/css", href = "customDark.css")
     ),
    setShadow(class = "shiny-plot-output"),
    setShadow( class = "box"),
    setShadow( class = "svg-container"),
  bsAlert("alert"),
  tabItems(
    # Initial INFO
    tabItem(tabName = "info",
            fluidRow(column(width = 4,
              box(width=12, 
                  uiOutput(outputId = "geneList"), 
                  uiOutput(outputId = "geneFile"),
                  uiOutput(outputId = "geneButton")
                  )
              ),
            column(width = 8,
            box(width=12,
                status = "info",
                title = h1(strong("Welcome to Enrich app 2020!") ),
            h3("Before starting using the app"),
            p("As a necessary initial element to start the analysis, 
                the program imports an object of the type DeseqDataSet, 
                generated by the DESeq function of the", 
              a("DESeq2", href="https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html"),
              "library. It has to be compress as an RDS object and upload 
                by clicking on the search engine button found in the upper left 
                corner of the app. Choose your object and enjoy your enrichment analysis ;)"),
            br(),
            h3("Get the app ready to use!"),
            p("First of all, select the specie of your experiment. 
              Then the option to enter your RDS object containing your 
              analysis will be unlocked. Upload it and wait for the loading 
              to be completed. When the loading symbol stops moving, 
              you can proceed to the next tab! "
              ),
            br(),
            p("Take advantage of every symbol of info" , icon("info-circle"), "that you might find.
              It can provide you with information that may be useful for 
              the proper functioning of the app. "
            ),
            br(),
            h3("How to download the app"),
            p("This app can be found on ",
              a("GitHub.", 
                href = "https://github.com/"))),
            )
            ), 
            br(),
        fluidRow(column(width = 6, offset = 3,
                    uiOutput("enrichbutton")
                    ))
    ),
    # preview tab
    tabItem(tabName = "preview",
            source(file = "ui-preview-tab.R",
            local=TRUE,
            encoding = "UTF-8"
            )$value),
    # kegg tab content
    tabItem(tabName = "kegg",
            source(file = "ui-kegg-tab.R",
                   local = TRUE,
                   encoding = "UTF-8"
                   )$value),
    # GO tab GO tab
    tabItem( tabName = "go",
             source(file = "ui-go-tab.R",
                    local = TRUE,
                    encoding = "UTF-8",
                    )$value),
    # GSEA tab
    tabItem( tabName = "gsea",
             source(file = "ui-gsea-tab.R",
                    local = TRUE,
                    encoding = "UTF-8",
                    )$value)
  ) # fin tab items
)# fin dashboardbody

########################################## UI #################################################

ui <- dashboardPage(title="Rnaseq viewer and report",
                    header,
                    sidebar,
                    body
) # fin del UI

########################################## SERVER #################################################
server <- function(input, output, session) {
  
  observeEvent(input$aboutButton, {
    shinyalert("Enrich app 2020", "Authors:
            Miriam Riquelme Pérez (corresponding author)
            Fernando Pérez Sanz
            For any suggestion or bug, please contact us
            miriam.riquelmep@gmail.com",
               imageUrl = "dna-svg-small-13.gif", 
               imageWidth = 200, imageHeight = 100)})
  
  specie <- reactive({input$specie})
  annotation <- reactive({input$annotation})
  validatedGene<- reactiveValues(list=NULL)
  data <- reactiveValues(df=NULL)
  kgg <- reactiveValues(all=NULL)
  kggDT <- reactiveValues(all=NULL)
  go <- reactiveValues(all=NULL)
  goDT <- reactiveValues(all=NULL)
  gene <- reactiveValues(lost=NULL)
  gsea <- reactiveValues(gsea=NULL)
  ## Leer datos ##########################
  observeEvent(input$geneButton,{
    # comprobaciones listado manual
    if( !is.null(input$geneList)){
      if(input$geneList!="" ){
        if (annotation() == "ensg") {
          if (length(which(grepl("^ENS", input$geneList, ignore.case = TRUE))) < length(input$geneList)  ) {
            shinyalert("Oops!!", "One or more genes are not 
            in ENSEMBL format",
                       type = "error")
          } else{
            validatedGene$list <- validateGeneList(input$geneList, specie(), annotation() )
            data$df <- formatData( validatedGene$list, specie(), annotation() )
            lost <- which(is.na(data$df$ENTREZID))
            gene$lost <- data$df$ENSEMBL[lost]
            data$df <- data$df[-lost, ]
            data$df$SYMBOL <- ifelse(is.na(data$df$SYMBOL), data$df$ENSEMBL, data$df$SYMBOL )
            }
        }
        if (annotation() == "symbol") {
          if (length(which(grepl("^ENS", input$geneList, ignore.case = TRUE))) ==  length(input$geneList) ) {
            shinyalert("Oops!!", "Looks like this entry is 
                       ENSEMBL please check your selection", 
                       type = "error")
          } else{
            validatedGene$list <- validateGeneList(input$geneList, specie(), annotation() )
            data$df <- formatData( validatedGene$list, specie(), annotation() )
            lost <- which(is.na(data$df$ENTREZID))
            gene$lost <- data$df$SYMBOL[lost]
            data$df <- data$df[-lost, ]
          }
          }
        }
      }
    ## comprobaciones cargar fichero
    if(!is.null(input$geneFile$datapath)){
      if(input$geneFile$datapath != "" ){
        validatedGene$list <- as.data.frame( readxl::read_xlsx(input$geneFile$datapath, sheet = 1))
        if (annotation() == "ensg") {
          if (length(which(grepl("^ENS", validatedGene$list[,1], ignore.case = TRUE))) < nrow(validatedGene$list) ) {
            shinyalert("Oops!!", "One or more genes are not 
            in ENSEMBL format",
                       type = "error")
          } else{
                data$df <- formatData( validatedGene$list, specie(), annotation() )
                lost <- which(is.na(data$df$ENTREZID))
                gene$lost <- data$df$ENSEMBL[lost]
                data$df <- data$df[-lost, ]
                data$df$SYMBOL <- ifelse(is.na(data$df$SYMBOL), data$df$ENSEMBL, data$df$SYMBOL )
          }
        }
        if (annotation() == "symbol") {
          if (length(which(grepl("^ENS", validatedGene$list[,1], ignore.case = TRUE))) ==  nrow(validatedGene$list)) {
            shinyalert("Oops!!", "Looks like this entry is 
                       ENSEMBL please check your selection", 
                       type = "error")
          } else{
                data$df <- formatData( validatedGene$list, specie(), annotation() )
                lost <- which(is.na(data$df$ENTREZID))
                gene$lost <- data$df$SYMBOL[lost]
                data$df <- data$df[-lost, ]
          }
        }
      }
    }
  })
  #TODO: Definir qué hacer con los NAs, eliminar, reportar, etc
  
  observeEvent(input$enrichButton,{
    kgg$all <- customKegg(data$df[,c("SYMBOL","ENTREZID") ], species = specie() )
    kggDT$all <- kegg2DT(kgg$all, data$df[,c("SYMBOL","ENTREZID") ] )
    go$all <- customGO(data$df[,c("SYMBOL","ENTREZID") ], species = "Mm")
    goDT$all <- go2DT(enrichdf = go$all, data = data$df[,c("SYMBOL","ENTREZID") ] )
    if( dim(data$df)[2]==4 ){
      gsea$gsea <- gseaKegg(data$df[, c("ENTREZID","rank")], specie() )
    }
  })
  
  ## Gene LIst ####################
  output$geneList <- renderUI({
    validate(need(specie(),""))
    validate(need(annotation(),""))
    textAreaInput(inputId = "geneList", label = "Input gene list ...", resize = "vertical")
  })
  ## Gene FIle #####################
  output$geneFile <- renderUI({
    validate(need(specie(),""))
    validate(need(annotation(),""))
    fileInput(inputId = "geneFile", label="...or upload file with gene list")
  })
  ## Boton validar ###############
  output$geneButton <- renderUI({
    validate(need(specie(),""))
    validate(need(annotation(),""))
    actionButton("geneButton", label = "Click to validate data")
  })
  ## boton enrich
  output$enrichbutton <- renderUI({
    validate(need(data$df, ""))
    actionBttn("enrichButton", label = "Click to run enrichment", size="lg", color="default", icon = icon("images"))
  })
  ##### tabla de prubea ##### para eliminar
  output$tabla <- renderTable({
    validate(need(data$df,""))
    print(data$df)
  })
}


shinyApp(ui, server)